project_name: gitp

before:
  hooks:
    - bun install

builds:
  - id: gitp
    builder: bun
    binary: gitp
    main: src/index.tsx
    dir: .
    targets:
      - linux-x64-modern
      - linux-arm64
      - darwin-x64
      - darwin-arm64
      - windows-x64-modern
    flags:
      - --compile
      - --minify
    env:
      - NODE_ENV=production

archives:
  - id: archive
    builds:
      - gitp
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: gitp
    repository:
      owner: sbcinnovation
      name: homebrew-tap
    directory: Formula
    commit_author:
      name: goreleaser
      email: actions@github.com
    homepage: https://github.com/sbcinnovation/gitp
    description: "Pretty git branch exploration for the terminal"
    license: MIT
    dependencies:
      - name: git
    test: |
      system "#{bin}/gitp", "--version"

scoops:
  - name: gitp
    repository:
      owner: sbcinnovation
      name: scoop-bucket
      branch: main
    directory: bucket
    commit_author:
      name: goreleaser
      email: actions@github.com
    homepage: https://github.com/sbcinnovation/gitp
    description: "Pretty git branch exploration for the terminal"
    license: MIT

nfpms:
  - id: linux-packages
    package_name: gitp
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - deb
      - rpm
    maintainer: SBC Innovation <opensource@sbcinnovation.com>
    description: Pretty git branch exploration for the terminal
    homepage: https://github.com/sbcinnovation/gitp
    license: MIT
    vendor: SBC Innovation
    bindir: /usr/bin
    dependencies:
      - git

release:
  prerelease: auto

snapshot:
  name_template: "SNAPSHOT-{{ .ShortCommit }}"
